FROM ubuntu:rolling
RUN apt update && apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    wget \
    mysql-client \
    docker \
    docker-compose \
    vim \
    ftp \
    zip \
 && rm -rf /var/lib/apt/lists/*
